### PR TITLE
fix the 404 error

### PR DESCRIPTION
**Pull request by nothingneko**

### CODE REVIEW

**Comment by koluckirafal** [comment]
The broken link was pointing to the archive with compiled topology binaries, which were recently moved to the `linux-firmware` repository; new link points to the snapshot of the repository, using which would require building topology files on the device.

A proper fix would be to either use [`linux-firmware` repo](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/intel/avs) as the new source of the topology binaries, or to install an updated `linux-firmware` package (version `20240811`, which probably isn't available in any mainstream distribution yet).

**Comment by mavr1iq** [comment]
> The broken link was pointing to the archive with compiled topology binaries, which were recently moved to the `linux-firmware` repository; new link points to the snapshot of the repository, using which would require building topology files on the device.
> 
> A proper fix would be to either use [`linux-firmware` repo](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/intel/avs) as the new source of the topology binaries, or to install an updated `linux-firmware` package (version `20240811`, which probably isn't available in any mainstream distribution yet).

i am not quite familliar with all of that stuff but how i can get it to work?

**Comment by nothingneko** [comment]
see #171

**Comment by ellyq** [comment]
> Are you going to merge it? if so, when? I am waiting for this to be get merged if this has solved the 404 error why not merging it?

How about you stop being an asshole to developers, who are currently on break because of burnout?

Treat people with respect, or fuck off.

**Pull request closed without merging**
