### PR TITLE
Add support for Immutable Spins of Fedora

### LINKED ISSUE #15: Fedora Silverblue?
I'm interested in trying out Fedora Silverblue, but the directory for the sound drivers is read-only. Is there another way or workaround to get audio to work on Fedora Silverblue?

I don't know much about Fedora Silverblue, but here is what I'm thinking:
- Make a package for `rpm-ostree`?
- Fork Fedora Silverblue to include the drivers by default?

### PR DESCRIPTION
**Pull request by ChocolateLoverRaj**
Closes #15

### CODE REVIEW

**Comment by QuantumChiliStorm** [comment]
@WeirdTreeThing Merge when?

**Comment by QuantumChiliStorm** [comment]
@WeirdTreeThing merge time please 🥹

**Comment by NyakoFox** [comment]
Hi, I'm curious why this was closed?

**Comment by WeirdTreeThing** [comment]
I don't use immutable distros and I have no interest in maintaining this feature.

**Pull request closed without merging**
